### ISSUE TITLE
App crashing a lot 😕

### ISSUE THREAD

**Issue by Madhan2307** [koiverse/ArchiveTune#150]
I can't open this app after installing the latest built... So request you to fix it as soon as possible please... I love this app much

**Comment by DeepakTCO** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/cbfad2f2-2bc4-4393-a087-eb8e6f507534" />
@koiverse i have been facing this issue since day one. As soon as I login the app crashes every time I open it. I hope you can fix it.

**Comment by Zareeff** [comment]
> > > <img alt="Image" width="1080" height="2000" src="https://private-user-images.githubusercontent.com/92305803/521954293-cbfad2f2-2bc4-4393-a087-eb8e6f507534.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3NzgzMzEsIm5iZiI6MTc2NDc3ODAzMSwicGF0aCI6Ii85MjMwNTgwMy81MjE5NTQyOTMtY2JmYWQyZjItMmJjNC00MzkzLWEwODctZWI4ZTZmNTA3NTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDE2MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYTEyMjZhMDcyMDcwNGI0YmMwMDkxMGEyYmFiYWEyNmRiMzg4ODk0MTllNDUxZjVhNmVjMGM2MmFlMzBiZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HMN4IKboqgNNFOFJ7-CCUudFPxcV5nFLYGPPQ-Fq6J8">
> > > [@koiverse](https://github.com/koiverse) i have been facing this issue since day one. As soon as I login the app crashes every time I open it. I hope you can fix it.
> > 
> > What happenes when you press "wait"?
> > 
> > Because sometimes the app "app isn't responding" but when i press "wait" it just works normally. When it doesn't, i just restart the app (sometimes force stop)
> 
> Nothing happens app gets stuck and I still can't use it and then the pop up comes again. Can you try logging out ? That's the only way I can stop it from crashing. 

Mine works completely fine after i press "wait".

Still though, it is quite annoying to see the pop up appearing countless times. Thankfully, koiverse noticed.

**Comment by koiverse** [comment]
I have fixed at least the potential causes, I hope your problem is resolved!

**Comment by DeepakTCO** [comment]
Thanks, it has been fixed finally. This can close all the crashing issue now.

**Comment by DeepakTCO** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/dffec436-4877-4cba-8688-ecf8d5964914" />
Also pls look into this too this has been annoying me too. Maybe just change all the text to white.

**Comment by Madhan2307** [comment]
> can you elaborate why you cannot install the archivetune latest build and show me which latest build type you're trying to installing

I am facing from the day one of installing the latest built... I have uninstalled and reinstalled the app several time ... But the issue remains the same .... Some times it displays some of code in it in a white screen .... Pls fix it as soon as possible.. hope you 🤝🏼

I added the screenshot of the issue... After displaying the code the app close suddenly.

![Image](https://github.com/user-attachments/assets/e25f8396-3c36-48e7-bd47-8a4b4f6270a8)

**Comment by koiverse** [comment]
alright, sent your full log here

**Comment by Madhan2307** [comment]
> The one solution is clear app data

Yeah it works... Tq for you constant support... Keep doing well 😊🤝🏼
